---
- name: Merge PostgreSQL configuration files
  assemble: src={{ datadir }}/pg_hba.d dest={{ datadir }}/pg_hba.conf backup=yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups.databaseservers }}"
  become: true
  notify:
    - Reload Postgres
  tags:
   - postgres-common
   - pgperms

- name: Reload Postgres
  service: name=postgresql state=reloaded
  delegate_to: "{{ db_master_host }}"
  become: true
  tags:
   - postgres-common
   - pgperms

- name: Restart Postgres
  service: name=postgresql state=restarted
  delegate_to: "{{ db_master_host }}"
  tags:
   - postgres-common
   - pgperms
