---
- name: Grant execute rights on obm-ca scripts
  file: path=/usr/share/obm-ca/{{ item }} mode=0750
  become: true
  with_items:
   - buildca.sh
   - createcert.sh
  tags: obm-ca

- name: Generate OBM-CA certificate file
  become: true
  command: >
      creates=/var/lib/obm-ca/cacert.pem
      /usr/share/obm-ca/buildca.sh
  tags: obm-ca

- name: Patch certificate creation script
  lineinfile: >
      line="sed -i "/CN=$1$/d" /var/lib/obm-ca/index.txt"
      dest=/usr/share/obm-ca/createcert.sh
      insertafter="#!/bin/bash"
      state=present
  become: true
  tags: obm-ca
