---
- name: YUM Install some common useful packages
  yum: 
      name: "{{ common_packages_list | join(',') }}"
      state: present
  become: true
  when: ansible_pkg_mgr == "yum"
  tags:
      - common
      - packages

- name: APT Install some common useful packages
  apt: 
      name: "{{ common_packages_list | join(',') }}"
      state: present
  become: true
  when: ansible_pkg_mgr == "apt"
  tags:
      - common
      - packages

- name: APT Remove package libio-socket-ip-perl
  apt: name=libio-socket-ip-perl
  when: ansible_pkg_mgr == "apt"
  tags:
      - common
      - packages
