---

- name: DEB sudo
  apt: name=sudo state=present
  when: ansible_os_family == "Debian"
  tags:
      - common
      - sudo

- name: Remove Defaults requiretty
  lineinfile:
    path: /etc/sudoers
    regexp: 'Defaults\s+requiretty\s*$'
    state: absent
  become: true
  tags:
      - common
      - sudo

- name: Disable requiretty if present in any other entries
  lineinfile:
    path: /etc/sudoers
    regexp: '^(Defaults.*?),?\s*requiretty\s*(,?)\s*(.*?)$'
    line: '\1\2\3'
    backrefs: yes
  become: true
  tags:
      - common
      - sudo
