---
- name: Remove bridge-nf-call
  sysctl: name=net.bridge.bridge-nf-call-{{ item }} state=absent reload=no
  with_items:
   - ip6tables
   - iptables
   - arptables
  changed_when: False
  tags:
      - common
      - sysctl
      - ipv6

- name: Disable IPv6
  sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1
  become: true
  tags:
      - common
      - sysctl
      - ipv6

- name: Increase kernel shared memory
  sysctl: name="kernel.shmmax" value=1073741824
  become: true
  tags:
      - common
      - sysctl
